include:
  - project: 'ihp/julia/julia-gitlab-ci-templates'
    ref: v1.3.1
    file: '/templates.gitlab-ci.yaml'

.julia.package_compiler.install:
  script:
    - |
      apt-get update
      apt-get install -y --no-install-recommends build-essential
    - julia ext/AvenueTools/scripts/install_package_compiler.jl

.julia.package_compiler.create_sysimage:
  script:
    - !reference [.julia.package_compiler.install, script]
    - julia --project ext/AvenueTools/scripts/create_sysimage.jl
  artifacts:
    expire_in: 1 week
    paths:
      - build/*.so

create_sysimage:
  stage: build
  parallel:
    matrix:
      - CI_JULIA_VERSION: ["1.6", "1.7"]
  extends:
    - .julia.setup
    - .julia.package_compiler.create_sysimage

validate:
  stage: test
  parallel:
    matrix:
      - CI_JULIA_VERSION: ["1.6", "1.7"]
  extends:
    - .julia.setup
  needs: ['create_sysimage']
  script:
    - !reference [.julia.version, script]
    - julia --project ext/AvenueTools/scripts/validate_sysimage.jl
